# Generated by Django 5.1.3 on 2026-06-29 10:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(db_index=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('icon_facility_available', models.ImageField(blank=True, null=True, upload_to='facilities/icons/')),
                ('icon_facility_unavailable', models.ImageField(blank=True, null=True, upload_to='facilities/icons/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(db_index=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('also_known_as', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('teaching_building', 'Teaching Building'), ('cultural_space', 'Cultural Space'), ('conference_events', 'Conference / Events Building'), ('library', 'Library'), ('social_building', 'Social Building'), ('student_services', 'Student Services'), ('research_laboratory', 'Research / Laboratories'), ('garden', 'Garden')], db_index=True, max_length=50)),
                ('campus', models.CharField(choices=[('old_aberdeen', 'Old Aberdeen'), ('foresterhill', 'Foresterhill'), ('hillhead', 'Hillhead')], db_index=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('weekday_open_time', models.TimeField(blank=True, null=True)),
                ('weekday_close_time', models.TimeField(blank=True, null=True)),
                ('saturday_open_time', models.TimeField(blank=True, null=True)),
                ('saturday_close_time', models.TimeField(blank=True, null=True)),
                ('sunday_holiday_open_time', models.TimeField(blank=True, null=True)),
                ('sunday_holiday_close_time', models.TimeField(blank=True, null=True)),
                ('opening_hrs_notes', models.TextField(blank=True)),
                ('id_access_needed', models.BooleanField(default=False)),
                ('additional_access_notes', models.TextField(blank=True)),
                ('uoa_map_link', models.URLField(blank=True)),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='locations/thumbnails/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SensoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(db_index=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LocationFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_facilities', to='sensemap.facility')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_facilities', to='sensemap.location')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='facilities',
            field=models.ManyToManyField(blank=True, related_name='locations', through='sensemap.LocationFacility', to='sensemap.facility'),
        ),
        migrations.CreateModel(
            name='LocationGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='locations/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='sensemap.location')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationSensoryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_sensory_profiles', to='sensemap.location')),
                ('sensory_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_sensory_profiles', to='sensemap.sensoryattribute')),
            ],
            options={
                'ordering': ['sensory_attribute__name'],
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(db_index=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('space_type', models.CharField(choices=[('study', 'Study Space'), ('quiet', 'Quiet Space'), ('social', 'Social Space'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='spaces/thumbnails/')),
                ('weekday_open_time', models.TimeField(blank=True, null=True)),
                ('saturday_open_time', models.TimeField(blank=True, null=True)),
                ('sunday_holiday_open_time', models.TimeField(blank=True, null=True)),
                ('opening_hrs_notes', models.TextField(blank=True)),
                ('wayfinding', models.TextField(blank=True)),
                ('sensory_experience', models.TextField(blank=True)),
                ('is_quiet_zone', models.BooleanField(default=False)),
                ('is_safe_space_neurodivergent_students', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='sensemap.location')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('is_anonymous', models.BooleanField(default=True)),
                ('reporter_name', models.CharField(blank=True, max_length=255)),
                ('reporter_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_reports', to='sensemap.location')),
                ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_reports', to='sensemap.space')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpaceFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_facilities', to='sensemap.facility')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_facilities', to='sensemap.space')),
            ],
            options={
                'ordering': ['facility__name'],
            },
        ),
        migrations.AddField(
            model_name='space',
            name='facilities',
            field=models.ManyToManyField(blank=True, related_name='spaces', through='sensemap.SpaceFacility', to='sensemap.facility'),
        ),
        migrations.CreateModel(
            name='SpaceSensoryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True)),
                ('sensory_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_sensory_profiles', to='sensemap.sensoryattribute')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_sensory_profiles', to='sensemap.space')),
            ],
            options={
                'ordering': ['sensory_attribute__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='locationfacility',
            constraint=models.UniqueConstraint(fields=('location', 'facility'), name='unique_location_facility'),
        ),
        migrations.AddConstraint(
            model_name='locationsensoryprofile',
            constraint=models.UniqueConstraint(fields=('location', 'sensory_attribute'), name='unique_location_sensory_attribute'),
        ),
        migrations.AddConstraint(
            model_name='feedbackreport',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('location__isnull', False), ('space__isnull', True)), models.Q(('location__isnull', True), ('space__isnull', False)), _connector='OR'), name='feedback_exclusive_target'),
        ),
        migrations.AddConstraint(
            model_name='spacefacility',
            constraint=models.UniqueConstraint(fields=('space', 'facility'), name='unique_space_facility'),
        ),
        migrations.AddConstraint(
            model_name='space',
            constraint=models.UniqueConstraint(fields=('location', 'name'), name='unique_space_name_per_location'),
        ),
        migrations.AddConstraint(
            model_name='spacesensoryprofile',
            constraint=models.UniqueConstraint(fields=('space', 'sensory_attribute'), name='unique_space_sensory_attribute'),
        ),
    ]
