# Generated by Django 5.1.3 on 2026-06-18 00:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensemap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='auditory',
        ),
        migrations.RemoveField(
            model_name='location',
            name='is_quiet_zone',
        ),
        migrations.RemoveField(
            model_name='location',
            name='olfactory',
        ),
        migrations.RemoveField(
            model_name='location',
            name='thermal',
        ),
        migrations.RemoveField(
            model_name='location',
            name='vestibular',
        ),
        migrations.RemoveField(
            model_name='location',
            name='visual',
        ),
        migrations.AddField(
            model_name='location',
            name='additional_access_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='location',
            name='also_known_as',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='location',
            name='campus',
            field=models.CharField(choices=[('old aberdeen', 'Old Aberdeen'), ('foresterhill', 'Foresterhill'), ('hillhead', 'Hillhead')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='id_access_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='opening_hrs_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='location',
            name='saturday_close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='saturday_open_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='sunday_holiday_close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='sunday_holiday_open_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='thumbnail_image',
            field=models.ImageField(blank=True, upload_to='locations/thumbnails/'),
        ),
        migrations.AddField(
            model_name='location',
            name='uoa_map_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='location',
            name='weekday_close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='weekday_open_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='location',
            name='facilities',
            field=models.ManyToManyField(blank=True, related_name='locations', to='sensemap.facility'),
        ),
        migrations.CreateModel(
            name='LocationGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='locations/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='sensemap.location')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('space_type', models.CharField(choices=[('study', 'Study Space'), ('quiet', 'Quiet Space'), ('social', 'Social Space'), ('sensory', 'Sensory Room'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_image', models.ImageField(blank=True, upload_to='spaces/thumbnails/')),
                ('weekday_open_time', models.TimeField(blank=True, null=True)),
                ('weekday_close_time', models.TimeField(blank=True, null=True)),
                ('saturday_open_time', models.TimeField(blank=True, null=True)),
                ('saturday_close_time', models.TimeField(blank=True, null=True)),
                ('sunday_holiday_open_time', models.TimeField(blank=True, null=True)),
                ('sunday_holiday_close_time', models.TimeField(blank=True, null=True)),
                ('opening_hrs_notes', models.TextField(blank=True)),
                ('wayfinding', models.TextField(blank=True)),
                ('sensory_experience', models.TextField(blank=True)),
                ('is_quiet_zone', models.BooleanField(default=False)),
                ('is_safe_space_neurodivergent_students', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facilities', models.ManyToManyField(blank=True, related_name='spaces', to='sensemap.facility')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='sensemap.location')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('is_anonymous', models.BooleanField(default=True)),
                ('reporter_name', models.CharField(blank=True, max_length=255)),
                ('reporter_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_reports', to='sensemap.location')),
                ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_reports', to='sensemap.space')),
            ],
        ),
        migrations.CreateModel(
            name='LocationSensoryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensory_profiles', to='sensemap.location')),
                ('sensory_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_profiles', to='sensemap.sensoryattribute')),
            ],
            options={
                'ordering': ['sensory_attribute__name'],
                'constraints': [models.UniqueConstraint(fields=('location', 'sensory_attribute'), name='unique_location_sensory_attribute')],
            },
        ),
        migrations.CreateModel(
            name='SpaceSensoryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sensory_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_profiles', to='sensemap.sensoryattribute')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensory_profiles', to='sensemap.space')),
            ],
            options={
                'ordering': ['sensory_attribute__name'],
                'constraints': [models.UniqueConstraint(fields=('space', 'sensory_attribute'), name='unique_space_sensory_attribute')],
            },
        ),
    ]
