# Generated by Django 5.1.3 on 2026-06-29 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensemap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='saturday_close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='sunday_holiday_close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='weekday_close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='icon_facility_available',
            field=models.ImageField(blank=True, null=True, upload_to='images/facilities/icons/'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='icon_facility_unavailable',
            field=models.ImageField(blank=True, null=True, upload_to='images/facilities/icons/'),
        ),
        migrations.AlterField(
            model_name='location',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/locations/thumbnail_images/'),
        ),
        migrations.AlterField(
            model_name='locationgalleryimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/locations/gallery/'),
        ),
        migrations.AlterField(
            model_name='locationsensoryprofile',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='space',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/spaces/thumbnail_images/'),
        ),
        migrations.AlterField(
            model_name='spacesensoryprofile',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
