# Generated by Django 5.1.3 on 2026-06-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensemap', '0002_location_accessible_toilet_location_building_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='space_type',
            field=models.CharField(choices=[('study', 'Study Space'), ('quiet', 'Quiet Space'), ('social', 'Social Space'), ('food_drink', 'Food & Drink'), ('facility', 'Facility'), ('sensory', 'Sensory Room'), ('other', 'Other')], db_index=True, max_length=50),
        ),
    ]
