# Generated by Django 5.1.3 on 2026-07-03 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensemap', '0002_space_saturday_close_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationfacility',
            options={'ordering': ['facility__name']},
        ),
        migrations.AlterField(
            model_name='facility',
            name='external_id',
            field=models.PositiveIntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='feedbackreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='external_id',
            field=models.PositiveIntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='locationsensoryprofile',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='sensoryattribute',
            name='external_id',
            field=models.PositiveIntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='space',
            name='external_id',
            field=models.PositiveIntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='spacesensoryprofile',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
