# Generated by Django 5.1.3 on 2026-07-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensemap', '0003_alter_locationfacility_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='space_type',
            field=models.CharField(choices=[('study', 'Study Space'), ('quiet', 'Quiet Space'), ('social', 'Social Space'), ('sensory', 'Sensory Room'), ('other', 'Other')], db_index=True, max_length=50),
        ),
    ]
