# Generated by Django 6.0.6 on 2026-07-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensemap', '0005_alter_location_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='physical_access',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='location',
            name='sensory_experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='location',
            name='wayfinding',
            field=models.TextField(blank=True),
        ),
    ]
