# Generated by Django 5.1.3 on 2026-07-14 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensemap', '0005_alter_location_category'),
        ('sensemap', '0006_location_physical_access_location_sensory_experience_and_more'),
    ]

    operations = [
    ]