# Generated by Django 6.0.7 on 2026-07-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensemap', '0004_alter_space_space_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='wayfinding',
            field=models.TextField(blank=True),
        ),
    ]
