# Generated by Django 5.1.3 on 2026-07-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensemap', '0006_merge_20260714_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationgalleryimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/locations/galleryimages/'),
        ),
    ]
