# Generated by Django 5.1.3 on 2026-07-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensemap', '0006_location_physical_access_location_sensory_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='space_type',
            field=models.CharField(choices=[('study', 'Study Space'), ('quiet', 'Quiet Space'), ('social', 'Social Space'), ('other', 'Other')], db_index=True, max_length=50),
        ),
    ]
