# Generated by Django 5.1.3 on 2026-07-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensemap', '0008_alter_location_category_alter_space_space_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.CharField(choices=[('teaching_building', 'Teaching Building'), ('cultural_space', 'Cultural Space'), ('conference_events', 'Conference / Events Building'), ('library', 'Library'), ('social_building', 'Social Building'), ('student_services', 'Student Services'), ('research_laboratory', 'Research / Laboratories'), ('garden', 'Garden'), ('sports_facility', 'Sports Facility'), ('support_building', 'Support Building'), ('nursery', 'Nursery'), ('shop', 'Shop'), ('cafe', 'Cafe')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='space',
            name='space_type',
            field=models.CharField(choices=[('study', 'Study Space'), ('quiet', 'Quiet Space'), ('social', 'Social Space'), ('other', 'Other')], db_index=True, max_length=50),
        ),
    ]
