# Generated by Django 5.1.3 on 2026-07-23 15:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensemap', '0008_alter_location_category_alter_space_space_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.CharField(choices=[('teaching_building', 'Teaching Building'), ('cultural_space', 'Cultural Space'), ('conference_events', 'Conference / Events Building'), ('library', 'Library'), ('social_building', 'Social Building'), ('student_services', 'Student Services'), ('research_laboratory', 'Research / Laboratories'), ('garden', 'Garden'), ('sports_facility', 'Sports Facility'), ('support_building', 'Support Building'), ('nursery', 'Nursery'), ('shop', 'Shop'), ('cafe', 'Cafe')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='space',
            name='space_type',
            field=models.CharField(choices=[('study', 'Study Space'), ('quiet', 'Quiet Space'), ('social', 'Social Space'), ('other', 'Other')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='FeedbackSensoryRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_anonymous', models.BooleanField(default=True)),
                ('reporter_name', models.CharField(blank=True, max_length=255)),
                ('reporter_email', models.EmailField(blank=True, max_length=254)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensory_feedback', to='sensemap.location')),
                ('sensory_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensory_feedback', to='sensemap.sensoryattribute')),
                ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensory_feedback', to='sensemap.space')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
