# Generated by Django 6.0.7 on 2026-07-27 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensemap', '0009_alter_location_category_alter_space_space_type'),
        ('sensemap', '0009_alter_location_category_alter_space_space_type_and_more'),
    ]

    operations = [
    ]
