# Generated by Django 5.1.3 on 2026-07-28 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensemap', '0010_alter_location_category'),
        ('sensemap', '0010_merge_20260727_1300'),
    ]

    operations = [
    ]
