# Generated by Django 6.0.7 on 2026-07-30 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensemap', '0011_merge_20260727_1400'),
        ('sensemap', '0011_merge_20260728_1642'),
    ]

    operations = [
    ]
