# Generated by Django 5.1.3 on 2026-08-10 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensemap', '0012_merge_20260730_2357'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedbackReport',
        ),
    ]
