# Generated by Django 6.0.3 on 2026-08-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensemap', '0013_delete_feedbackreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='space_type',
            field=models.CharField(choices=[('study', 'Study Space'), ('quiet', 'Quiet Space'), ('social', 'Social Space'), ('food_drink', 'Food & Drink'), ('sport', 'Sport / Fitness'), ('outdoor', 'Outdoor'), ('other', 'Other')], db_index=True, max_length=50),
        ),
    ]
