# Generated by Django 6.0.3 on 2026-08-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensemap', '0014_alter_space_space_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='space_type',
            field=models.CharField(choices=[('study', 'Study Space'), ('quiet', 'Quiet Space'), ('social', 'Social Space'), ('food_drink', 'Food & Drink'), ('sport', 'Sport / Fitness'), ('outdoor', 'Outdoor')], db_index=True, max_length=50),
        ),
    ]
