# Generated by Django 6.0.3 on 2026-08-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensemap', '0015_alter_space_space_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='floor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='space',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
