# Generated by Django 6.0.3 on 2026-08-12 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensemap', '0016_space_floor_space_latitude_space_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationsensoryprofile',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
