# Generated by Django 6.0.7 on 2026-08-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensemap', '0017_alter_locationsensoryprofile_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='space_type',
            field=models.CharField(choices=[('study', 'Study Space'), ('quiet', 'Quiet Space'), ('social', 'Social Space'), ('food_drink', 'Cafeteria'), ('sport', 'Sport / Fitness'), ('outdoor', 'Outdoor')], db_index=True, max_length=50),
        ),
    ]
