# Generated by Django 5.1.3 on 2026-08-17 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensemap', '0017_alter_locationsensoryprofile_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='physical_access',
        ),
        migrations.RemoveField(
            model_name='location',
            name='sensory_experience',
        ),
        migrations.RemoveField(
            model_name='location',
            name='wayfinding',
        ),
        migrations.RemoveField(
            model_name='space',
            name='sensory_experience',
        ),
        migrations.AlterField(
            model_name='locationsensoryprofile',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='space',
            name='space_type',
            field=models.CharField(choices=[('study', 'Study Space'), ('quiet', 'Quiet Space'), ('social', 'Social Space'), ('cafeteria', 'Cafeteria'), ('sport', 'Sport / Fitness'), ('outdoor', 'Outdoor')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='spacesensoryprofile',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
