# Generated by Django 6.0.7 on 2026-08-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensemap', '0018_alter_space_space_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.CharField(choices=[('teaching_building', 'Teaching Building'), ('cultural_space', 'Cultural Space'), ('conference_events', 'Conference / Events Building'), ('library', 'Library'), ('social_building', 'Social Building'), ('student_services', 'Student Services'), ('student_accommodation', 'Student Accommodation'), ('research_laboratory', 'Research / Laboratories'), ('garden', 'Garden'), ('sports_facility', 'Sports Facility'), ('support_building', 'Support Building'), ('nursery', 'Nursery'), ('shop', 'Shop'), ('cafe', 'Cafeteria')], db_index=True, max_length=50),
        ),
    ]
