# Generated by Django 5.1.3 on 2026-08-20 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensemap', '0013_restore_feedbackreport_table'),
        ('sensemap', '0018_alter_space_space_type'),
    ]

    operations = [
    ]
