# Generated by Django 6.0.7 on 2026-08-19 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensemap', '0013_restore_feedbackreport_table'),
        ('sensemap', '0018_alter_space_space_type'),
    ]

    operations = [
    ]
