# Generated by Django 5.1.3 on 2026-08-17 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensemap', '0018_alter_space_space_type'),
        ('sensemap', '0018_remove_location_physical_access_and_more'),
    ]

    operations = [
    ]
