# Generated by Django 5.1.3 on 2026-08-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensemap', '0019_merge_20260817_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensoryattribute',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/sensory_attributes/icons/'),
        ),
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.CharField(choices=[('teaching_building', 'Teaching Building'), ('cultural_space', 'Cultural Space'), ('conference_events', 'Conference / Events Building'), ('library', 'Library'), ('social_building', 'Social Building'), ('student_services', 'Student Services'), ('student_accommodation', 'Student Accommodation'), ('research_laboratory', 'Research / Laboratories'), ('garden', 'Garden'), ('sports_facility', 'Sports Facility'), ('support_building', 'Support Building'), ('nursery', 'Nursery'), ('shop', 'Shop'), ('cafe', 'Cafeteria')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='space',
            name='space_type',
            field=models.CharField(choices=[('study', 'Study Space'), ('quiet', 'Quiet Space'), ('social', 'Social Space'), ('cafeteria', 'Cafeteria'), ('food_drink', 'Cafeteria'), ('sport', 'Sport / Fitness'), ('outdoor', 'Outdoor')], db_index=True, max_length=50),
        ),
    ]
