# Generated by Django 5.1.3 on 2026-08-19 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensemap', '0021_facility_created_by_facility_updated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('record_id', models.CharField(max_length=100)),
                ('record_name', models.CharField(max_length=255)),
                ('location_id_snapshot', models.PositiveIntegerField(blank=True, null=True)),
                ('location_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], db_index=True, max_length=20)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('previous_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensory_map_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['model_name', 'changed_at'], name='sensemap_au_model_n_6c5222_idx'), models.Index(fields=['action', 'changed_at'], name='sensemap_au_action_0d420d_idx')],
            },
        ),
    ]
