# Generated by Django 6.0.7 on 2026-08-19 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensemap', '0019_alter_location_category'),
        ('sensemap', '0021_facility_created_by_facility_updated_by_and_more'),
    ]

    operations = [
    ]
