# Generated by Django 5.1.3 on 2026-08-19 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensemap', '0019_alter_location_category'),
        ('sensemap', '0022_auditlog'),
    ]

    operations = [
    ]
