# Generated by Django 6.0.7 on 2026-08-19 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensemap', '0022_merge_20260819_1653'),
        ('sensemap', '0023_merge_0019_alter_location_category_0022_auditlog'),
    ]

    operations = [
    ]
